# Generated by Django 4.2.1 on 2023-05-20 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shoppingapp", "0002_cart"),
        ("sellerapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerOrderHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("order placed", "order placed"),
                            ("out for delivery", "out for delivery"),
                        ],
                        default="order placed",
                        max_length=100,
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shoppingapp.user",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sellerapp.product",
                    ),
                ),
            ],
        ),
    ]
